admin-console: false
admin-console-token: S3Cr3tP4$$phrAsE
alias-load-balancer: false
append-user-to-subdomain: false
append-user-to-subdomain-separator: '-'
authentication: true
authentication-keys-directory: /git/sish/deploy/pubkeys/
authentication-password: S3Cr3tP4$$phrAsE
banned-aliases: ""
banned-countries: ""
banned-ips: ""
banned-subdomains: localhost
bind-any-host: false
bind-hosts: ""
bind-random-aliases: false
bind-random-aliases-length: 4
bind-random-ports: false
bind-random-subdomains: false
bind-random-subdomains-length: 4
cleanup-unbound: true
cleanup-unbound-timeout: 5s
config: config.sunny5.yml
debug: false
domain: sunny5.de
force-requested-aliases: false
force-requested-ports: false
force-requested-subdomains: false
geodb: false
http-address: :2020
http-load-balancer: false
http-port-override: 0
https: false
https-address: :2021
https-certificate-directory: /git/sish/deploy/ssl/
https-ondemand-certificate: false
https-ondemand-certificate-accept-terms: false
https-ondemand-certificate-email: ""
https-port-override: 0
idle-connection: true
idle-connection-timeout: 60m
load-templates: true
load-templates-directory: /git/sish/templates/*
localhost-as-all: true
log-to-client: false
log-to-file: true
log-to-file-compress: false
log-to-file-max-age: 28
log-to-file-max-backups: 3
log-to-file-max-size: 500
log-to-file-path: /tmp/sish.log
log-to-stdout: true
ping-client: true
ping-client-interval: 5s
ping-client-timeout: 5s
port-bind-range: 0,10000-65535
private-key-location: /git/sish/deploy/keys/ssh_key
#private-key-passphrase: S3Cr3tP4$$phrAsE
proxy-protocol: false
proxy-protocol-listener: false
proxy-protocol-policy: use
proxy-protocol-timeout: 200ms
proxy-protocol-use-timeout: false
proxy-protocol-version: "1"
redirect-root: true
redirect-root-location: https://github.com/antoniomika/sish
service-console: false
service-console-token: ""
ssh-address: :2222
tcp-aliases: true
tcp-load-balancer: false
time-format: 2006/01/02 - 15:04:05
verify-dns: true
verify-ssl: true
whitelisted-countries: ""
whitelisted-ips: ""
