version: '3.7'

services:
  letsencrypt:
    image: adferrand/dnsrobocert:latest
    container_name: letsencrypt-dns
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/etc/letsencrypt
      - ./le-config.yml:/etc/dnsrobocert/config.yml
    restart: always
  sish:
    image: antoniomika/sish:latest
    #stdin_open: true
    #tty: true
    container_name: sish
    depends_on: 
      - letsencrypt
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./pubkeys:/pubkeys
      - ./keys:/keys
      - ./ssl:/ssl
    command: |
      --ssh-address=:2222
      --http-address=:2020
      --https-address=:2021
      --https=false
      --https-certificate-directory=/ssl
      --authentication-keys-directory=/pubkeys
      --private-key-location=/keys/ssh_key
      --bind-random-aliases=false
      --bind-random-ports=false
      --bind-random-subdomains=false
      --authentication=true
      --tcp-aliases=true
      --log-to-file=true
      --log-to-file-path=/var/log/sish 
      --authentication-password="supersecret"
      --idle-connection-timeout=60m
      --ping-client-interval=5s
      --domain=sunny5.de
    network_mode: host
    restart: always
